[package]
name = "libpapyrus"
version = "0.1.0"
authors = ["Daniel Nunes <daniel.henri.nunes@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
